import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Aside from "@/components/core/Aside";
import Header from "@/components/core/Header";
import Player from "@/components/Player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + "text-primary font-metrophobic"}>
        <div
          className={`relative flex flex-col md:flex-row gap-1 md:pl-2 md:pr-4 min-h-screen`}
        >
          <Aside className="relative md:sticky top-0 pt-4 h-fit md:h-screen bg-background" />
          <section className="flex-auto">
            <Header
              className={`fixed md:sticky w-full top-0 z-50 bg-background`}
            />
            {children}
          </section>
        </div>
        <Player />
      </body>
    </html>
  );
}
