import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Aside from "@/components/core/Aside";
import Header from "@/components/core/Header";
import Player from "@/components/Player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + "text-primary font-metrophobic"}>
        <div className={`relative flex gap-6 pl-2 pr-4 min-h-screen`}>
          <Aside className="sticky top-0 pt-4 h-screen bg-background" />
          <section className="flex-auto">
            <Header className={`sticky top-0 z-50 bg-background`} />
            <main className="flex min-h-screen flex-col">{children}</main>
          </section>
        </div>
        <Player />
      </body>
    </html>
  );
}
